### ISSUE TITLE
Ini harus daftar ke toped open api kah?

### ISSUE THREAD

**Issue by yukebrillianth** [plvhx/tokopedia-php-sdk#2]
Ini harus daftar ke toped open api kah? atau langsung pakai?

**Comment by plvhx** [comment]
Langsung pakai gan

Pada tanggal Sen, 19 Okt 2020 17:03, Yuke Brilliant H. <
notifications@github.com> menulis:

**Comment by plvhx** [comment]
tapi harus daftar dulu lah, kan creds nya dari sana

**Comment by yukebrillianth** [comment]
kalau tidak star seller tidak bisa kan?

**Comment by plvhx** [comment]
Waduh lek perkoro star utowo ndak star ra paham aku

Pada tanggal Sen, 19 Okt 2020 18:35, Yuke Brilliant H. <
notifications@github.com> menulis:

**Comment by yukebrillianth** [comment]
oke tak cobak disek

**Comment by plvhx** [comment]
Oyi

Pada tanggal Sen, 19 Okt 2020 18:39, Yuke Brilliant H. <
notifications@github.com> menulis:

**Comment by yukebrillianth** [comment]
Documentation?

**Comment by plvhx** [comment]
Sek aras arasen nulis dokumentasi aku

Pada tanggal Sen, 19 Okt 2020 20:19, Yuke Brilliant H. <
notifications@github.com> menulis:

**Comment by plvhx** [comment]
Woco ae sors e

Pada tanggal Sel, 20 Okt 2020 15:25, Paulus Gandung <gandung@slackerc0de.us>
menulis:
