### ISSUE TITLE
Encryption requirement

### ISSUE THREAD

**Issue by deantheiceman** [plvhx/tokopedia-php-sdk#3]
Tokopeida adds new encryption requirement 
https://developer.tokopedia.com/openapi/guide/#/encryption/

**Comment by plvhx** [comment]
yeah, i'm currently working on that improvement based on it.

**Comment by deantheiceman** [comment]
Today is the last day to update

**Comment by plvhx** [comment]
yeah, I know, but now I currently working on important office chores. if you're eager to implement it, please work and send your pull request to me.

**Comment by plvhx** [comment]
check src/Service/Encryption.php

**Comment by deantheiceman** [comment]
Nice. I'm confused about the decrypt requirement, we need to decrypt the receiver name

**Comment by deantheiceman** [comment]
Will you add support for data decryption?
